ALTER TABLE talks ADD COLUMN dead BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE blog_posts ADD COLUMN dead BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN dead BOOLEAN NOT NULL DEFAULT false;
